In [30]:
import seaborn as sns
import numpy as np
import pandas as pd

In [31]:
from numpy.linalg import inv

In [32]:
df=sns.load_dataset("titanic")
df=df[df.describe().columns]

In [33]:
df.fillna(20,inplace=True)

     survived  pclass   age  sibsp  parch     fare
0           0       3  22.0      1      0   7.2500
1           1       1  38.0      1      0  71.2833
2           1       3  26.0      0      0   7.9250
3           1       1  35.0      1      0  53.1000
4           0       3  35.0      0      0   8.0500
..        ...     ...   ...    ...    ...      ...
886         0       2  27.0      0      0  13.0000
887         1       1  19.0      0      0  30.0000
888         0       3  20.0      1      2  23.4500
889         1       1  26.0      0      0  30.0000
890         0       3  32.0      0      0   7.7500

[891 rows x 6 columns]

In [34]:
df.shape

(891, 6)

In [35]:
x=df.drop('fare',axis=1)
y=df['fare']

In [36]:
x.shape,y.shape

((891, 5), (891,))

In [37]:
x['constant']=1

In [38]:
x.shape

(891, 6)

In [39]:
x.T.shape

(6, 891)

In [40]:
term1=inv(np.dot(x.T,x))

In [41]:
term1.shape

(6, 6)

In [42]:
x.T.shape

(6, 891)

In [43]:
term2=np.dot(term1,x.T)

In [44]:
term2.shape

(6, 891)

In [45]:
y.shape

(891,)

In [46]:
np.dot(term2,y)

array([  6.0813274 , -33.00277574,  -0.11829276,   6.00953338,
         9.97994984, 102.39550396])

In [47]:
x.columns

Index(['survived', 'pclass', 'age', 'sibsp', 'parch', 'constant'], dtype='str')

In [48]:
df["Predicted_Fare"] = (
    102
    + 6.08 * df["survived"]
    - 33 * df["pclass"]
    - 0.11 * df["age"]
)

In [53]:
beta = np.linalg.inv(x.T @ x) @ x.T @ y

In [54]:
df=sns.load_dataset("tips")
df.shape

(244, 7)

In [55]:
df=df[['total_bill','tip','size']].iloc[0:10,:]

In [56]:
df

   total_bill   tip  size
0       16.99  1.01     2
1       10.34  1.66     3
2       21.01  3.50     3
3       23.68  3.31     2
4       24.59  3.61     4
5       25.29  4.71     4
6        8.77  2.00     2
7       26.88  3.12     4
8       15.04  1.96     2
9       14.78  3.23     2